# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcpm',
            name='actual_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
